version: '1.0'
name: daily_build
displayName: daily_build
triggers:
  trigger: manual
  push:
    branches:
      precise:
        - master
stages:
  - name: stage-c55b27b6
    displayName: BuildProjet
    strategy: naturally
    trigger: auto
    executor:
      - qsaker
    steps:
      - step: build@gcc
        name: build_gcc
        displayName: Build
        gccVersion: '10.3'
        commands:
          - apt-get update --fix-missing -y
          - apt-get install libgl1-mesa-dev -y
          - ''
          - qmake -v
          - ''
          - 'pip install aqtinstall   '
          - aqt install-qt linux desktop 6.5.3 gcc_64 -m qtcharts qtserialbus qtserialport
          - ''
          - ls
          - ''
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./bin
        caches: []
        notify: []
        strategy:
          retry: '0'
