name: build-windows
on:
  schedule:
    - cron: '0 0 * * *'
#on:
#  push:
#    branches:
#      - master
jobs:
  build:
    name: Build
    runs-on: windows-2019
    strategy:
      matrix:
        target: [desktop]
        arch: [win64_msvc2019_64]
        version: [5.15.2, 6.5.3]
        include:
          - version: 5.15.2
            cmake-prefix-path: 'lib/cmake/Qt5'
            modules: 'qtcharts'
          - version: 6.5.3
            cmake-prefix-path: 'lib/cmake/Qt6'
            moudles: 'qtcharts qtserialbus qtserialport qtwebsockets'
    steps:
      - name: Pull code
        uses: actions/checkout@v1
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.version }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          dir: ${{ github.workspace }}
          modules: ${{ matrix['moudles']}}
      - name: build-msvc
        shell: cmd
        run: |
          mkdir build
          cd build
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          cmake -DWITH_TOOLS:BOOL=OFF -DCMAKE_PREFIX_PATH='${{ github.workspace }}/Qt/${{ matrix.version }}/${{ matrix.arch }}/${{ matrix.cmake-prefix-path }}' -DCMAKE_BUILD_TYPE=Release -G "NMake Makefiles" ../
          nmake
